# This Dockerfile is used for the development environment via `docker compose`

FROM ruby:3.2.4

RUN apt-get update -qq \
  && apt-get install -y build-essential git nano postgresql-client libpq-dev \
  nodejs libssl-dev apt-transport-https ca-certificates libvips42 \
  chromium chromium-driver

RUN mkdir /bt
WORKDIR /bt
COPY Gemfile /bt/Gemfile
COPY Gemfile.lock /bt/Gemfile.lock

COPY . /bt
