# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/ticket_sale_options', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # TicketSaleOption. As you add validations to TicketSaleOption, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      TicketSaleOption.create! valid_attributes
      get ticket_sale_options_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      ticket_sale_option = TicketSaleOption.create! valid_attributes
      get ticket_sale_option_url(ticket_sale_option)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_ticket_sale_option_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      ticket_sale_option = TicketSaleOption.create! valid_attributes
      get edit_ticket_sale_option_url(ticket_sale_option)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new TicketSaleOption' do
        expect do
          post ticket_sale_options_url, params: { ticket_sale_option: valid_attributes }
        end.to change(TicketSaleOption, :count).by(1)
      end

      it 'redirects to the created ticket_sale_option' do
        post ticket_sale_options_url, params: { ticket_sale_option: valid_attributes }
        expect(response).to redirect_to(ticket_sale_option_url(TicketSaleOption.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new TicketSaleOption' do
        expect do
          post ticket_sale_options_url, params: { ticket_sale_option: invalid_attributes }
        end.not_to change(TicketSaleOption, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post ticket_sale_options_url, params: { ticket_sale_option: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested ticket_sale_option' do
        ticket_sale_option = TicketSaleOption.create! valid_attributes
        patch ticket_sale_option_url(ticket_sale_option), params: { ticket_sale_option: new_attributes }
        ticket_sale_option.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the ticket_sale_option' do
        ticket_sale_option = TicketSaleOption.create! valid_attributes
        patch ticket_sale_option_url(ticket_sale_option), params: { ticket_sale_option: new_attributes }
        ticket_sale_option.reload
        expect(response).to redirect_to(ticket_sale_option_url(ticket_sale_option))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        ticket_sale_option = TicketSaleOption.create! valid_attributes
        patch ticket_sale_option_url(ticket_sale_option), params: { ticket_sale_option: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested ticket_sale_option' do
      ticket_sale_option = TicketSaleOption.create! valid_attributes
      expect do
        delete ticket_sale_option_url(ticket_sale_option)
      end.to change(TicketSaleOption, :count).by(-1)
    end

    it 'redirects to the ticket_sale_options list' do
      ticket_sale_option = TicketSaleOption.create! valid_attributes
      delete ticket_sale_option_url(ticket_sale_option)
      expect(response).to redirect_to(ticket_sale_options_url)
    end
  end
end
